### ISSUE TITLE
"Invalid position! Chunks are not loaded here." on space elevator placement

### ISSUE THREAD

**Issue by osmarks** [taterjr/Space-Station#1]
I tried to place a space elevator, and got that message, as well as "This is not a valid position" in chat.

**Comment by osmarks** [comment]
I've checked the code, and it looks like you probably just need to take out the bit in control.lua checking whether the chunks on the space side are generated, as they should be generated as the linkingSurface chunks anyway.

**Comment by taterjr** [comment]
I tried to put linking_surface.request_to_generate_chunks before checking if the chunk was generated but it still made the error. So I just left linking_surface.request_to_generate_chunks after checking.

**Comment by taterjr** [comment]
This should be fixed in 0.1.7.
